package com.arrizabalaga
/*
 * This Spock specification was auto generated by running 'gradle init --type groovy-library'
 * by 'arrizabalaga' at '7/6/14 9:47 AM' with Gradle 1.12
 *
 * @author arrizabalaga, @date 7/6/14 9:47 AM
 */
import spock.lang.Specification

class NodeSpec extends Specification{
    def "Should add children in order"() {
        setup:
        Node parent=new Node(id:1)
        Node childA=new Node(id:2)
        Node childB=new Node(id:3)
        when:
        parent.addChildren(childA)
        then:
        parent.children==[childA]
        when:
        parent.addChildren(childB)
        then:
        parent.children==[childA,childB]
    }
}
