package com.arrizabalaga
/*
 * This Spock specification was auto generated by running 'gradle init --type groovy-library'
 * by 'arrizabalaga' at '7/6/14 9:47 AM' with Gradle 1.12
 *
 * @author arrizabalaga, @date 7/6/14 9:47 AM
 */


import com.arrizabalaga.BuildTree
import spock.lang.Specification

class NodeSpec extends Specification{
    def "someLibraryMethod returns true"() {
        setup:
        BuildTree lib = new BuildTree()
        when:
        def result = lib.someLibraryMethod()
        then:
        result == true
    }
}
